/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8694b1c0-7f85-4183-87a8-d7932bda1e14",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yOyCG6C3x",
    "aws_user_pools_web_client_id": "69390d9137k4br2ffgtp505hcm",
    "oauth": {
        "domain": "bm1gbg4fkc9z-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://main.d1x0trs6a9kp1g.amplifyapp.com",
        "redirectSignOut": "https://main.d1x0trs6a9kp1g.amplifyapp.com",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
